#!/usr/bin/env node
// LOC report via cloc. Requires `cloc` on PATH (https://github.com/AlDanial/cloc).
//
// Counts only git-tracked files via `--vcs=git`, so anything in .gitignore
// (node_modules, .wwebjs_auth, logs, *.db, .next, .cache, e2e/db, ...) is
// skipped automatically. Belt-and-braces: explicit --exclude-dir / --exclude-ext
// also passed in case the repo is not a git checkout.
//
// Usage:
//   npm run loc                    # summary by language
//   npm run loc -- --by-file       # per-file breakdown
//   npm run loc -- --include-lang=TypeScript,YAML
//
// Anything after `--` is forwarded verbatim to cloc.

import { spawnSync } from 'node:child_process'

// Do NOT add 'db' here: it would also match the legitimate src/db/ drizzle
// folder. Runtime sqlite under e2e/db is gitignored, so --vcs=git skips it.
const EXCLUDE_DIRS = [
  'node_modules',
  'dist',
  'build',
  '.next',
  '.cache',
  '.wwebjs_auth',
  '.wwebjs_cache',
  'logs',
  '.git',
].join(',')

const EXCLUDE_EXTS = ['log', 'db', 'db-journal', 'db-shm', 'db-wal', 'tsbuildinfo'].join(',')

// Skip autogenerated files (lockfiles, drizzle migrations + snapshots, Next
// type shim). The regex must be quoted because `|` and `.` get mangled by
// cmd.exe under shell:true, and `--not-match-d` parens are also unsafe there.
const NOT_MATCH_FILES = [
  'package-lock\\.json',
  '.*_snapshot\\.json',
  '0000_init\\.sql',
  'next-env\\.d\\.ts',
].join('|')

const passthrough = process.argv.slice(2)
const isWin = process.platform === 'win32'
const q = (v) => (isWin ? `"${v}"` : v)

const args = [
  '.',
  '--vcs=git',
  `--exclude-dir=${EXCLUDE_DIRS}`,
  `--exclude-ext=${EXCLUDE_EXTS}`,
  `--not-match-f=${q(NOT_MATCH_FILES)}`,
  ...passthrough,
]

const r = spawnSync('cloc', args, {
  stdio: 'inherit',
  shell: process.platform === 'win32',
})

if (r.error) {
  console.error('cloc not found on PATH. Install: https://github.com/AlDanial/cloc')
  process.exit(127)
}

process.exit(r.status ?? 0)
